### PR TITLE
Fixed nodejs-express-version to match new requirements

### PR DESCRIPTION
**Pull request by dorianweidler**
Made it match the latest requirements (POST instead of GET)

### CODE REVIEW

**Review by bitterblue — CHANGES_REQUESTED** [review]
That POST tripped me up, too.
Could you please add a README.md, explaining the steps I need to take to make your solution run?

**Comment by TimoFreiberg** [comment]
> That POST tripped me up, too.

Me too. The `Date` response header as well

**Comment by bitterblue** [comment]
I assume, that's a header included by micronaut by default, and that's why @slu-it had it in the description.

**Comment by TimoFreiberg** [comment]
It made it a lot more interesting, so anyway it was a happy mistake

**Comment by dorianweidler** [comment]
Added a README.md.

**Review by bitterblue — APPROVED** [review]

**Comment by slu-it** [comment]
actually examples were taken from some random site with an example raw `HTTP POST` to get the syntax right ;)

**Pull request merged**
